### ISSUE TITLE
Upgrade near-indexer-primitives to support version 0.15

### ISSUE THREAD

**Issue by frol** [near/near-lake-framework-rs#48]
https://github.com/near/near-lake-framework-rs/blob/d4bd0bd9c7024f454200543fc935fcd4caa19d39/Cargo.toml#L30

Given the breaking changes in the near-indexer-primitives (many of the previously base64-encoded String fields were turned into proper `Vec<u8>` types, so base64 is only happening on serialization and deserialization now), near-lake-framework-rs will need to also release a breaking release.

**Comment by khorolets** [comment]
I already have a draft for that. Once I ensure nothing needs to be changed or improved I'll cut a release. This should happen pretty soon.

**Comment by khorolets** [comment]
@frol I've found 3 related PRs in Indexer for Explorer so far:

- https://github.com/near/near-indexer-for-explorer/commit/a7a33a6414bba020485b3227e0cc214802f4aad7
- https://github.com/near/near-indexer-for-explorer/commit/f720c796bc8f5252c6dae015b7a27f5707355aa1
- https://github.com/near/near-indexer-for-explorer/commit/e6974ea7db230e552fba474c4908f4b9d236b7e6

Do you remember any other code changes related to the breaking change? 

(I am collecting the info to properly describe the reasoning behind the update)
