### ISSUE TITLE
Shard fetcher makes one extra request per block? 

### ISSUE THREAD

**Issue by flmel** [near/near-lake-framework-rs#49]
Hey I was reading trough and got wondered doesn't this fetcher make one extra request per block ? https://github.com/near/near-lake-framework-rs/blob/main/src/s3_fetchers.rs#L86 ? wouldn't it   
`(0..block_view.chunks.len() - 1  as u64) ` be  better instead of `(0..block_view.chunks.len() as u64)` ? The 4th shard is with shard_id: 3

**Comment by frol** [comment]
@flmel `0..4` is `[0; 4)` range in Rust, so it will unroll into `0, 1, 2, 3`
