### ISSUE TITLE
LEP-071: Introduce a middleware concept to the Lake Framework

### ISSUE THREAD

**Issue by khorolets** [near/near-lake-framework-rs#71]
| Status | ACCEPTED |
| :--- | :--- |
| Proposed on | Apr 28, 2023 |
| Decision made on | May 8, 2023 |
| Proposed by | @khorolets |
| Reviewers invited | @pkudinov @frol @telezhnaya  @morgsmccauley @roshaans @gabehamilton @eduohe |
| **Decision makers** | @pkudinov @khorolets @telezhnaya @morgsmccauley @roshaans |

## Actuality

Lake Framework aims to make developers' lives easier, so we are constantly trying to improve the framework itself so it is simpler and flexible simultaneously. We are trying to build our proposal on top of real-world use cases.

And here's one of the cases we want to make a proposal to improve.

### Parent transaction for the receipt

When indexing, you can choose to focus solely on Receipts (or Actions in upcoming versions 0.8.0 and beyond, which introduce Lake Primitives). Typically, when following this approach, you would record a parent transaction where the chain of events began once you encounter an Action that meets your criteria. However, neither the protocol nor the Lake Framework provides any tools for retrieving such a transaction from a Receipt or Action.

In the various indexers we run, such as the Indexer for Explorer, we've had to implement this functionality differently. For this project, we've introduced an in-memory cache that maintains the relationship between a Receipt and the transaction from the moment the transaction is observed until we observe the very last Receipt in that chain. At present, we don't see a more efficient way to achieve this.

As this task is quite common, many indexer developers come up with their own solutions. We'd like to provide a ready-to-use solution for all of them. However, some developers may not require it, so we cannot afford to include our solution in the standard library of the Lake Framework.

Moreover, we believe that there are many other cases where developers face similar challenges and it would be helpful to have a mechanism for sharing solutions. That's why we came up with this proposal.

## The proposal

Single word: **middlewares**.

We propose introducing the concept of middleware into the Lake Framework, starting from the upcoming high-level release 0.8.0. This would allow developers to write their own middleware or use existing ones while indexing.

To illustrate this idea, let's revisit the example of the parent transaction problem from the Actuality section. We could publish a library called `lake-parent-transaction` that provides a `ParentTransactionCache` middleware which developers could add to the Lake Framework indexer:

```rust
use lake_parent_transaction::ParentTransactionCache;

LakeBuilder::default()
    .mainnet()
    .start_block_height(0)
    .middleware(ParentTransactionCache)
    .build()
    .unwrap()
    .run(handle_block);
```

This middleware would function similarly to the user-defined indexing function (`handle_block`). It would receive a `Block` structure as input, perform some actions, and potentially modify the `Block`. The modified[^1] `Block` would then be used as input to the user-defined function itself.

Of course, it's possible to accomplish similar tasks without introducing middleware. However, imagine having several different tasks that could be accomplished using a few published middlewares:

```rust
use lake_parent_transaction::ParentTransactionCache;
use lake_other_case:OtherCaseMiddleware;
use lake_even_more:EvenMoreMiddleware;

LakeBuilder::default()
    .mainnet()
    .start_block_height(0)
    .middleware(ParentTransactionCache)
    .middleware(OtherCaseMiddleware)
    .middleware(OtherCaseMiddleware)
    .build()
    .unwrap()
    .run(handle_block);
```

By allowing developers to easily reuse and share middleware, we can avoid reinventing the wheel and streamline the development process. Moreover, this approach allows people to share their work through open source in a standardized way.

[^1]: Rust imposes some limitations, so we can't change the `Block` structure itself. Instead, we'll need to introduce traits and accept and return something like `impl Block`.

## Action items

- [ ] Create an implementation of the first publishable middleware (most likely the one described in the proposal)
- [ ] Design and implement changes to the Lake Framework and Lake Primitives to allow the usage of the middleware
- [ ] Create demonstrative examples:
  - [ ] Using an existing middleware
  - [ ] Creating your own
- [ ] Update the documentation
- [ ] Create documentation about how to share your middleware with the community

**Comment by telezhnaya** [comment]
Does it mean we will be able to drop 1/3 codebase of Indexer for Explorer?
I love the proposal

**Comment by gabehamilton** [comment]
Nice. This looks like it enables an Enrichment step. Middleware looks like a good implementation.  

1. In other place we're talking about configuring a context object to expose the additional data. Should the additional data here be exposed through a context object?

2. Could we share caching implementations between projects? 
Something like: using `.middleware(ParentTransactionCache)` pulls in the RPC cache crate and uses it to cache transactions; more enrichment middleware might store balances or contracts in that same cache; use all the middleware and you end up with a copy of explorer in that cache :-) 

3. Maybe we add more helper methods over time so that invocation chain can alternatively be
```
let processor = stream
    .filterAndReturnActions(myFilter)
    .enrich(ParentTransactionType)
    .transform(myDataTransform)
    .writeToDB(myDatabaseConnection, myQuery);

LakeBuilder::default().mainnet().start_block_height(0)
    .middleware(ParentTransactionCache)
    .run(processor);
```

**Comment by morgsmccauley** [comment]
The proposal looks really good! Nice job 👏🏽 

Most (JS) middleware implementations I've seen follow the "onion" principal, where each middleware can execute code before and after the next. Do you see any benefit in doing something similar? One potential use case could be an error handling middleware handles errors returned from `handle_block()`.

**Comment by khorolets** [comment]
> Do you see any benefit in doing something similar? 

Perhaps, I've got your question wrong, but I believe the code from the proposal corresponds to that "onion" principal you refer to. 

```rust
LakeBuilder::default()
    .mainnet()
    .start_block_height(0)

    .middleware(ParentTransactionCache)
    .middleware(OtherCaseMiddleware)
    .middleware(OtherCaseMiddleware)
//   ^^^^^^^^^^
    .build()
    .unwrap()
    .run(handle_block);
```

Please, elaborate if you think I misunderstood.

**Comment by frol** [comment]
I like the direction of thought, but I would explore if it is better to integrate middleware into contexts:

```rust
use lake_parent_transaction::ParentTransactionCache;
use lake_other_case:OtherCaseMiddleware;
use lake_even_more:EvenMoreMiddleware;

struct MyContext {
    parent_transaction_cache: lake_parent_transaction::ParentTransactionCache,
    ...
}

let my_context = MyContext::new();

LakeBuilder::default()
    .mainnet()
    .start_block_height(0)
    .build()
    .unwrap()
    .run_with_context(handle_block, my_context);

// ...

fn handle_block(block, context) {
    let parent_transaction_or_none = context.parent_transaction_cache.get(block.receipt[0].receipt_id);
    // ...
    context.update(block); // impl for MyContext which will call .update() on all the child contexts
}
```

Another concern I have in mind is concurrency. Will ParentTransactionCache require `concurrency = 1`?

**Comment by khorolets** [comment]
@frol 
> but I would explore if it is better to integrate middleware into contexts
It doesn't make sense to me, since context is flexible by design, nothing prevents a developer from using it for such a case.

With the middleware on the other hand developer will have something like this:

```rust
use lake_parent_transaction::ParentTransactionCache;

// Run a lake
LakeBuilder::default()
    .mainnet()
    .start_block_height(0)
    .middleware(ParentTransactionCache)
    .build()
    .unwrap()
    .run(handle_block);
// ...

fn handle_block(block: impl Block) -> anyhow::Result<()> {
// ParentTransactionCache receives the `impl Block` structure and modifies it, so the Receipt
// has a getter `parent_transaction_hash() -> Option<CryptoHash>`
   println!("{:?}", block.receipts().collect()[0].parent_transaction_hash());
}
```

BTW It's still a question of how to achieve this API. I am going to find out during the implementation.

> Another concern I have in mind is concurrency. Will ParentTransactionCache require concurrency = 1?

In order to work properly, yes. It's a matter of proper settings, I think the recommendations and requirements should come from the middleware's README.

**Comment by morgsmccauley** [comment]
> Perhaps, I've got your question wrong, but I believe the code from the proposal corresponds to that "onion" principal you refer to.

My point mainly refers to the internals of `ParentTransactionCache`. What does this function accept, when is it called in relation to other middlewares? "Onion" in this case means each middleware _wraps_ the next, and the last wraps the core handler, in this case `handle_block`.

So say we had two middlewares; `ErrorHandlerMiddleware`, and `ParentTransactionMiddleware`, and the main handler `handle_block`. Each of these would wrap the next, allowing code execution before and after the next. So if each middleware did execute before and after, the execution sequence would be:
- `ErrorHandlerMiddleware`
    - `ParentTransactionMiddleware`
        - `handle_block`
    - `ParentTransactionMiddleware`
- `ErrorHandlerMiddleware` 

This is achieved by each middleware taking the next as an argument, therefore having control over when it get's executed and what to do with the result of that execution. You wouldn't always want/need to execute before and after, but that option is open to you.

One example I see this being useful is the `ErrorHandlerMiddleware` which could `match` on the return value and have some specific logic to handle different failure cases.

I'm not sure how easy something like this would be to achieve, especially after you mentioned the complexities of transforming `Block` within a given middleware. Just an option to consider if you think it would provide benefit :)

**Comment by frol** [comment]
Just a random idea for the `ParentTransactionCache`, there could be some public API that would keep the whole history (for the rare cases when you need to start from a random point in history)

**Comment by khorolets** [comment]
Thank you, everybody, for your valuable input on this.

Having comments like these:

> My point mainly refers to the internals of ParentTransactionCache...

> Just a random idea for the ParentTransactionCache...

I realize `ParentTransactionCache` introduces more fun to you than a middleware concept :) I believe we've gathered all the comments and I am starting to figure out how to implement it.

Just to clarify, there are some unknowns. My intention was to provide the "goal" I am aiming for but I have no idea whether it is even possible like this. However, I need to have a target API design to aim for, but I am going to try to stick to the proposed design as much as possible.

So I am marking it as decision is made and will move to the implementation.

**Comment by khorolets** [comment]
In the #73 PR you can see where did I get.

At that point, I realized that it is still possible to try to implement the proposal, however, the way middlewares have to be written is far beyond the "comfort" level I am trying to keep here.

We had a call with @frol to discuss possibilities and the only question we get to was "Do we really need it since it is achievable with Contexts?" And the answer was "No".

A different approach in middleware implementation is collapsed next. We gave up understanding the level of complexity required to write a Middleware following the approach. You can have a look.
<details>
<summary>Different middleware implementation approach</summary>

```rust
trait Middleware {
    fn init_other_middleware(&mut self, m: impl Middleware);
}

struct MiddlewareA<M: Middleware> {
    nested_middleware: Option<M>,
}
impl Middleware for MiddlewareA<M: Middleware> {
    type Block = MiddlewareABlock;
    
    fn init_other_middleware<NestedMiddleware>(&mut self, m: NestedMiddleware) {
        self.nested_middleware = m;
    }
}

struct MiddlewareB<M: Middleware> {
    nested_middleware: Option<M>,
}

struct Lake<M> {
    middlewares: M,
}

struct Block {}

impl<M> Lake<M> {
    fn middleware<NewMiddleware>(self, new_middleware: NewMiddleware<M>) -> Lake<NewMiddleware<M>> {
        Lake {
            middlewares: new_middleware.init_other_middleware(self.middleware)
        }
    }

    fn run<F>(&self, f: F)
    where F: Fn(impl Block + M::Block) {
        loop {
            let b = Block {};
            // self.middlewares.before_run(&b);
            // f(&b);
            // self.middlewares.after_run(&b);
            self.middlewares.run(b, f);
            break;
        }
    }
}

fn main() {
    let lake = Lake {};
    lake
        .middleware(Logging)
        .middleware(Cache)
        .run(|b| {});
}
```

</details>

---

As a result, I am recording a failure here and marking this LEP as "DECLINED".

I thank everybody for their participation.
