### ISSUE TITLE
Add s3_fetchers to get a block or chunk without infinite retries

### ISSUE THREAD

**Issue by kobayurii** [near/near-lake-framework-rs#97]
**Problem Overview**

When utilizing the s3_fetchers within the lake_framework, a persistent issue has been encountered. Specifically, the problem manifests as an infinite loop during the fetching process, and notably, this loop occurs without triggering any error messages or notifications.

**Symptoms Encountered**

**1. Infinite Loop:** The fetch operation doesn’t terminate as expected and continues indefinitely.
**2. Absence of Error Notification:** Despite the loop, the process does not produce any explicit error messages or notifications to indicate the issue, making it challenging to identify the root cause.

**Desired Functionality**

There's a need for enhanced functionality within the s3_fetchers module:

**1. Controlled Block or Chunk Fetching:** Introduce the capability to control the fetching process in a manner that allows for fetching blocks of data rather than entering an infinite loop.
**2. Error Handling & Notification:** Implement a mechanism that enables the module to appropriately detect errors during the fetch process and trigger notifications or return specific error codes to the user. This will provide more insight into the issues occurring during fetching.

**Comment by khorolets** [comment]
Fixed with #98 in 0.7.5
